baseURL = 'http://downloads.openhwgroup.org.s3-website-eu-west-1.amazonaws.com/'
languageCode = "en-us"
title = "OpenHW Group Downloads"
themesDir = "themes"
theme = "hugo-whisper-theme"
staticDir = ["static", "themes/hugo-whisper-theme/static"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[markup]
  [markup.goldmark.renderer]
    unsafe=true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

# [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1

# [[menu.main]]
#     name = "Docs"
#     url = "/docs/"
#     weight = 2

[params]
  google_analytics_id=""
  homepage_button_text = ''

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"
